linters:
  ErbSafety:
    # TODO: [@rhymes] re-enable this and fix the violations,
    # see https://github.com/Shopify/erb-lint#ErbSafety
    enabled: false
  SelfClosingTag:
    enabled: false
  ParserErrors:
    exclude:
      - '**/app/views/pages/_editor_guide_text.html.erb'
  SpaceInHtmlTag:
    exclude:
      - '**/app/views/pages/_editor_guide_text.html.erb'
  AllowedScriptType:
    enabled: true
    allowed_types:
      - 'text/javascript'
      - 'text/x-tmpl'
      - 'application/ld+json'
    allow_blank: true
    disallow_inline_scripts: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Max: 289
        Exclude:
          - '**/app/views/comments/_comment_proper.html.erb'
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
        Exclude:
          - '**/app/views/feedback_messages/index.html.erb'
          - '**/app/views/layouts/_styles.html.erb'
          - '**/app/views/liquid_embeds/show.html.erb'
          - '**/app/views/moderations/mod.html.erb'
          - '**/app/views/pages/onboarding.html.erb'
          - '**/app/views/partnerships/show.html.erb'
          - '**/app/views/partnerships/index.html.erb'
