inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.0.5
  DisplayStyleGuide: true
  DisableDefaultCops: false
  ExtraDetails: true
  UseCache: true
  # CacheRootDirectory: "tmp/.cache/rubocop_cache/"
  # CacheRootDirectory: "tmp"
  MaxFilesInCache: 5
  NewCops: enable # opt-in to new cops by default
  ActiveSupportExtensionsEnabled: true
  # DocumentationBaseURL: https://docs.rubocop.org/rubocop

  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: true

# # Reason: Prefer Hashes without extreme indentation
# # https://docs.rubocop.org/rubocop/cops_layout.html#layoutfirsthashelementindentation
# Layout/FirstHashElementIndentation:
#   EnforcedStyle: consistent

# Reason: Currently disabled in .rubocop_todo.yml
# https://docs.rubocop.org/rubocop/cops_layout.html#layoutlinelength
Layout/LineLength:
  Max: 320 # Default of 120 causes a duplicate entry in generated todo file


# Reason: only doing this in development as some production environments (Heroku) are sensitive to local FS writes, and besides -- it's just not proper to have a dev-mode tool do its thing in production.
# Include: **/Rakefile, **/*.rake
Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

# # Reason:
# # https://docs.rubocop.org/rubocop/cops_lint.html#lintuselessaccessmodifier
# Lint/UselessAccessModifier:
#   ContextCreatingMethods:
#     - class_methods

# ## Disable most Metrics/*Length cops
# # Reason: those are often triggered and force significant refactors when this happend
# #         but the team feel they are not really improving the code quality.

# # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsblocklength
# Metrics/BlockLength:
#   Enabled: false

# # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsclasslength
# Metrics/ClassLength:
#   Enabled: false

# # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmethodlength
# Metrics/MethodLength:
#   Enabled: false

# # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmodulelength
# Metrics/ModuleLength:
#   Enabled: false

# ## End Disable Metrics/*Length cops

# # Reason: Currently disabled in .rubocop_todo.yml
# # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsabcsize
# Metrics/AbcSize:
#   Exclude:
#     - db/*migrate/**/*

# # Reason: Currently disabled in .rubocop_todo.yml
# # https://docs.rubocop.org/rubocop/cops_metrics.html#metricscyclomaticcomplexity
# Metrics/CyclomaticComplexity:
#   Exclude:
#     - db/*migrate/**/*

# # Reason:
# # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsparameterlists
# Metrics/ParameterLists:
#   CountKeywordArgs: false

# # Reason: Prevailing style is argument file paths
# # https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsfilepath
# Rails/FilePath:
#   EnforcedStyle: arguments

# # Reason: Prevailing style uses numeric status codes, matches RSpec/Rails/HttpStatus
# # https://docs.rubocop.org/rubocop-rails/cops_rails.html#railshttpstatus
# Rails/HttpStatus:
#   EnforcedStyle: numeric

# # Reason: Allowed in `tootctl` CLI code and in boot ENV checker
# # https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsexit
# Rails/Exit:
#   Exclude:
#     - 'config/boot.rb'

# # Reason: Some single letter camel case files shouldn't be split
# # https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecfilepath
# # RSpec/FilePath:
# #   CustomTransform:
# #     ActivityPub: activitypub # Ignore the snake_case due to the amount of files to rename
# #     DeepL: deepl
# #     FetchOEmbedService: fetch_oembed_service
# #     JsonLdHelper: jsonld_helper
# #     OEmbedController: oembed_controller
# #     OStatus: ostatus
# #     NodeInfoController: nodeinfo_controller # NodeInfo isn't snake_cased for any of the instances
# #   Exclude:
# #     - 'spec/config/initializers/rack_attack_spec.rb' # namespaces usually have separate folder
# #     - 'spec/lib/sanitize_config_spec.rb' # namespaces usually have separate folder

# # Reason:
# # https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecnamedsubject
# RSpec/NamedSubject:
#   EnforcedStyle: named_only

# # Reason: Prevailing style choice
# # https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecnottonot
# RSpec/NotToNot:
#   EnforcedStyle: to_not

# # Reason: Prevailing style uses numeric status codes, matches Rails/HttpStatus
# # https://docs.rubocop.org/rubocop-rspec/cops_rspec_rails.html#rspecrailshttpstatus
# RSpec/Rails/HttpStatus:
#   EnforcedStyle: numeric

# # Reason:
# # https://docs.rubocop.org/rubocop/cops_style.html#styleclassandmodulechildren
# Style/ClassAndModuleChildren:
#   Enabled: false

# # Reason: Classes mostly self-document with their names
# # https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
# Style/Documentation:
#   Enabled: false

# # Reason: Enforce modern Ruby style
# # https://docs.rubocop.org/rubocop/cops_style.html#stylehashsyntax
# Style/HashSyntax:
#   EnforcedStyle: ruby19_no_mixed_keys

# # Reason:
# # https://docs.rubocop.org/rubocop/cops_style.html#stylenumericliterals
# Style/NumericLiterals:
#   AllowedPatterns:
#     - \d{4}_\d{2}_\d{2}_\d{6} # For DB migration date version number readability

# # Reason:
# # https://docs.rubocop.org/rubocop/cops_style.html#stylepercentliteraldelimiters
# Style/PercentLiteralDelimiters:
#   PreferredDelimiters:
#     '%i': '()'
#     '%w': '()'

# # Reason: Prefer less indentation in conditional assignments
# # https://docs.rubocop.org/rubocop/cops_style.html#styleredundantbegin
# Style/RedundantBegin:
#   Enabled: false

# # Reason: Overridden to reduce implicit StandardError rescues
# # https://docs.rubocop.org/rubocop/cops_style.html#stylerescuestandarderror
# Style/RescueStandardError:
#   EnforcedStyle: implicit

# # Reason: Simplify some spec layouts
# # https://docs.rubocop.org/rubocop/cops_style.html#stylesemicolon
# Style/Semicolon:
#   AllowAsExpressionSeparator: true

# # Reason: Originally disabled for CodeClimate, and no config consensus has been found
# # https://docs.rubocop.org/rubocop/cops_style.html#stylesymbolarray
# Style/SymbolArray:
#   Enabled: false

# # Reason:
# # https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainarrayliteral
# Style/TrailingCommaInArrayLiteral:
#   EnforcedStyleForMultiline: 'comma'

# # Reason:
# # https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainhashliteral
# Style/TrailingCommaInHashLiteral:
#   EnforcedStyleForMultiline: 'comma'