# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: insta
services:
  db:
    image: postgres:16-alpine
    shm_size: 256mb
    build:
      context: .
      dockerfile: postgres/Dockerfile
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
    environment:
      POSTGRES_USER: insta
      POSTGRES_PASSWORD: insta
      POSTGRES_DB: insta_development
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
     - db_data:/var/lib/postgresql/data
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:5432:5432"
  testdb:
    image: postgres:16-alpine
    shm_size: 256mb
    build:
      context: .
      dockerfile: postgres/Dockerfile
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
    environment:
      POSTGRES_USER: insta
      POSTGRES_PASSWORD: insta
      POSTGRES_DB: insta_test
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
     - testdb_data:/var/lib/postgresql/data
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:5433:5433"
  redis:
    image: redis:7.2.5-alpine
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
     - redis_data:/var/lib/redis/data
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
volumes:
  db_data:
  testdb_data:
  redis_data:
