name: Report an issue
description: Report a Insta issue.
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        This template is used for reporting a Insta issue. [Example](https://github.com/dambar08/insta/tree/canary/examples)-related issues should be reported using [this](https://github.com/dambar08/insta/issues/new?assignees=&labels=type%3A+example%2Ctemplate%3A+bug&template=2.example_bug_report.yml) issue template instead.

        Feature requests should be opened in [discussions](https://github.com/dambar08/insta/discussions/new?category=ideas). For more information about opening a feature request, [read more](https://github.com/dambar08/insta/blob/canary/contributing/core/adding-features.md).

        Documentation requests should also be opened in [discussions](https://github.com/dambar08/insta/discussions/new?category=ideas).

        Before opening a new issue, please do a [search](https://github.com/dambar08/insta/issues) of existing issues and :+1: upvote the existing issue instead. This will result in a quicker resolution.

        If you need help with your own project, you can:
        - Start a discussion in the ["Help"](https://github.com/dambar08/insta/discussions/categories/help) section.
  - type: input
    attributes:
      label: Link to the code that reproduces this issue
      description: |
        A link to a **public** [GitHub repository](https://github.com/dambar08/insta/tree/canary/examples/reproduction-template).

        If you decide to create your own minimal reproduction, please make sure test on canary. It is highly likely that the issue you are experiencing is already fixed in the canary version.

        **Skipping this/providing an invalid link will result in the issue being closed.**
      placeholder: 'https://github.com/user/my-minimal-insta-issue-reproduction'
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, based on the linked reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
      placeholder: |
        1. Start the application in development (bin/rails s)
        2. Click X
        3. Y will happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: |
        A clear and concise description of what the bug is (e.g., screenshots, logs, etc.), and what you expected to happen.

        **Skipping this/failure to provide complete information of the bug will result in the issue being closed.**
      placeholder: 'Following the steps from the previous section, I expected A to happen, but I observed B instead.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Provide environment information
      description: Please run `bin/rails about` in the root directory of your project and paste the results.
      render: bash
      placeholder: |
        About your application's environment
        Rails version             7.2.2.2
        Ruby version              ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin23]
        RubyGems version          3.5.22
        Rack version              3.1.16
        Middleware                ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, Warden::Manager, Bullet::Rack
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - 'Not sure'
        - 'After'
        - 'Connection'
        - 'Cookies'
        - 'CSS'
        - 'Draft Mode'
        - 'cacheComponents'
        - 'Dynamic Routes'
        - 'Error Handling'
        - 'Error Overlay'
        - 'Headers'
        - 'Lazy Loading'
        - 'Instrumentation'
        - 'Internationalization (i18n)'
        - 'Linking and Navigating'
        - 'Linting'
        - 'Loading UI and Streaming'
        - 'Markdown (MDX)'
        - 'Metadata'
        - 'Middleware'
        - 'Module Resolution'
        - 'Not Found'
        - 'Output'
        - 'Routing'
        - 'Routing'
        - 'Performance'
        - 'Hotwire'
        - 'Stimulus'
        - 'Webpack'
        - 'React'
        - 'Redirects'
        - 'Runtime'
        - 'Script (script)'
        - 'Testing'
        - 'TypeScript'
        - 'SWC'
        - 'Use Cache'

    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which stage(s) are affected? (Select all that apply)
      multiple: true
      options:
        - 'bin/rails (local)'
        - 'bin/rails assets:precompile (local)'
        - 'Cloud provider (Deployed)'
        - 'Other (Deployed)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate. For example, where are you deploying your application (Cloud Provider, Bare Metal, Docker, other platform)? Is it only reproducible on that platform, or locally too? Is the issue only happening in a specific browser? etc.
      placeholder: |
        I tested my reproduction against different canary releases, and the first one that introduced the bug was "version 1.0.0", since reverting to "version 1.0.0" works.

        or

        I am hosting via Docker with the recommended `output: "standalone"` option, and if I remove that option or try a different hosting option, I cannot reproduce the same issue.
